### ISSUE TITLE
Doesn

### ISSUE THREAD

**Issue by knussear** [ONLYOFFICE/plugin-wordscounter#3]

**Comment by knussear** [comment]
Installed per instructions, wordcount shows in plugins, and opens side bar on select and clik, but no counts are provided. Using ONLYOFFICE Desktop Editors version 6.1.0.90
on Pop_os (ubuntu) 20.10

**Comment by ShockwaveNN** [comment]
Just checked on Pop_os 20.10 and everything seems fine for me
![image](https://user-images.githubusercontent.com/668524/104198278-19570580-5437-11eb-8f51-3dc27404a594.png)

Didn't you forget to select text by any chance?

**Comment by knussear** [comment]
Here is what I'm getting. Any suggestions on how to fix it?

**Comment by ShockwaveNN** [comment]
You didn't attach any new info, didn't you forgot screenshot and info about insulation methid

**Comment by knussear** [comment]
Here is a screenshot. I only get blank fields

**Comment by ShockwaveNN** [comment]
Are you trying to attach screenshot to email? Github not work that way

And I asking again for your installation method/package type

**Comment by knussear** [comment]
Ah - yes I was. Here is the screenshot.  
![wordcount](https://user-images.githubusercontent.com/2953219/104222200-cfe6c600-53f6-11eb-9ca3-9bde8049ac35.jpg)

**Comment by ShockwaveNN** [comment]
Thanks for screenshot, but are you just ignoring my question about your installation method?

**Comment by knussear** [comment]
Missed the question. I copied the code.js, config.json, and index.html files to a folder, zipped it, and renamed to .plugin. I got this per the instructions here https://api.onlyoffice.com/plugin/installation

"Adding a plugin to the desktop editors
You need to take the plugin files (config.json, index.html and pluginCode.js), archive them and change the file extension to .plugin. After that click the Plugin button plugin button and select the Manage Plugins option. The plugin manager window will be opened:"

**Comment by ShockwaveNN** [comment]
No, this is question not about how you installed plugin, but how did you installed DesktopEditors, via deb, snap, flatpak or something else?

If you not sure - that is the output of 
`dpkg -l | grep onlyoffice`
and
`snap list | grep onlyoffice` 
and
`flatpak list | grep onlyoffice`

**Comment by knussear** [comment]
I installed the flatpack from the popshop

**Comment by ShockwaveNN** [comment]
> I installed the flatpack from the popshop

Could you try to install DesktopEditors from deb repo via [instruction](https://helpcenter.onlyoffice.com/installation/desktop-install-ubuntu.aspx) and see if problem still actual

**Comment by ShockwaveNN** [comment]
I've just checked flatpak version installed via 
```
flatpak install flathub org.onlyoffice.desktopeditors
```
And everything seems fine

If your problem persists even on `*.deb` installation - could you attach packed plugin itself, maybe problem in some missing files

**Comment by knussear** [comment]
I removed the flatpack and  installed the deb version and I get the same behavior. Attaching packed.

I do not see an option to attach the file here.

**Comment by ShockwaveNN** [comment]
> I do not see an option to attach the file here.

You should zip your `*.plugin` file and attach here

**Comment by knussear** [comment]
OK 
[wordcount.zip](https://github.com/ONLYOFFICE/plugin-wordscounter/files/5812007/wordcount.zip)

**Comment by ShockwaveNN** [comment]
@knussear Yeah, your plugin is not working for me and missing an icon

Why are copied only 3 file to `.plugin` archive?

It need whole structure from here, several folders and several files

**Comment by knussear** [comment]
Per the instructions.

**Comment by ShockwaveNN** [comment]
Attach your file which cannot be installed

**Comment by knussear** [comment]
[wordscounter-master.plugin.zip](https://github.com/ONLYOFFICE/plugin-wordscounter/files/5814665/wordscounter-master.plugin.zip)
This one does not install for me, trying yours now. Thanks for sending.

**Comment by knussear** [comment]
And can confirm that yours is working for me.

**Comment by ShockwaveNN** [comment]
> This one does not install for me, trying yours now. Thanks for sending.
You should not have root folder inside `plugin` file, `index.html` and all other files should be at root of your archive

**Comment by ShockwaveNN** [comment]
> And can confirm that yours is working for me.

In that case I'll close this issue
