### ISSUE TITLE
Can't add plugin on macOS

### ISSUE THREAD

**Issue by ThatOneCalculator** [ONLYOFFICE/plugin-wordscounter#7]
Hi!

I downloaded the ZIP archive of this repo, called it `wordcount.plugin`, and went to Plugins > Add plugin, and nothing happened. I restarted the program, still no dice. 

macOS version is 10.15. It seems to work fine on my Linux machine. This might be because macOS also uses the `.plugin` file extension for internal use.

**Comment by ShockwaveNN** [comment]
@ThatOneCalculator Could you attach plugin file? It may be incorrectly zipped
